# Generated by Django 5.2.9 on 2025-12-27 12:02

import bookings.validators
import django.db.models.deletion
import django_jalali.db.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('national_id', models.CharField(max_length=10, validators=[bookings.validators.validate_national_id])),
                ('mobile', models.CharField(max_length=11, validators=[bookings.validators.validate_mobile_number])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('booking_date_jalali', django_jalali.db.models.jDateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('referral_source', models.CharField(blank=True, max_length=100)),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('privacy_accepted', models.BooleanField(default=False)),
                ('newsletter_opt_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('hot_desk', 'Hot Desk'), ('dedicated_desk', 'Dedicated Desk'), ('private_office', 'Private Office'), ('meeting_room', 'Meeting Room')], default='hot_desk', max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('cancelled', 'Cancelled')], max_length=20)),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('changed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='bookings.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.space'),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_jalali', django_jalali.db.models.jDateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='bookings.space')),
            ],
            options={
                'verbose_name_plural': 'Availabilities',
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['national_id'], name='bookings_bo_nationa_e03720_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['mobile'], name='bookings_bo_mobile_90aebd_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date_jalali'], name='bookings_bo_booking_e9173c_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['space', 'booking_date_jalali', 'status'], name='bookings_bo_space_i_59a573_idx'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['space', 'date_jalali'], name='bookings_av_space_i_12b10a_idx'),
        ),
    ]
